variables:
  SAST_EXCLUDED_ANALYZERS: "semgrep-sast,gosec-sast"
  DOCKER_DRIVER: overlay2

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never

include:
  - local: 'engine/.gitlab-ci.yml'
  - local: 'ui/.gitlab-ci.yml'
  - local: 'cloudformation/.gitlab-ci.yml'

empty-job:
  stage: test
  script:
    - echo 'success'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - engine/**/*
        - ui/**/*
        - cloudformation/**/*
      when: never

ci-checker:
  stage: test
  image: alpine:3.15
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ui/**/*
        - cloudformation/**/*
        - packer/**/*
      when: never
  before_script:
    - apk add --no-cache curl jq bash
  variables:
    INPUT_COMMANDS: |
      env
      echo 'Migration has been completed'
    INPUT_DBNAME: "test_small"
    INPUT_OBSERVATION_INTERVAL: 10
    INPUT_MAX_LOCK_DURATION: 1
    INPUT_MAX_DURATION: 600
    INPUT_DOWNLOAD_ARTIFACTS: "true"
    # MR_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/notes?body=${COMMENT}
    MR_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/notes/1032432395
    COMMENT: |
      This is a multi-line test comment
      - With GitLab **Markdown** :sparkles:
      - Created by [postgres-ai/migration-ci-action][1]
      
      [1]: https://github.com/marketplace/actions/database-lab-realistic-db-testing-in-ci
      
      ### Summary
        | Status | Passed  :white_check_mark: |
        |:---:| ---  |
        | Session | #872  |
        | Project | - |
        | DLE version | v3.1.1-15-g1db723b-20220616-0755 |
        | Data state at | 2022-06-12 00:00:06 +0000 UTC |
        | Duration    | 44s|
  script:
    # Run CI checker.
    - echo "Run CI checker"
    # - bash ./engine/scripts/run_checker.sh
    - bash run_checker.sh

    # Download artifacts.
    - echo "Download artifacts"
    - cat response.json || true

    # Post summary.
    - echo "Post summary"

    - | 
      curl --request PUT --header "PRIVATE-TOKEN: ${CI_CHECKER_TOKEN}" --data-urlencode "body=${COMMENT}" "${MR_URL}"

