variables:
  SAST_EXCLUDED_ANALYZERS: "semgrep-sast,gosec-sast"
  DOCKER_DRIVER: overlay2

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never

include:
  - local: 'engine/.gitlab-ci.yml'
  - local: 'ui/.gitlab-ci.yml'
  - local: 'cloudformation/.gitlab-ci.yml'

empty-job:
  stage: test
  script:
    - echo 'success'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - engine/**/*
        - ui/**/*
        - cloudformation/**/*
      when: never

ci-checker:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ui/**/*
        - cloudformation/**/*
        - packer/**/*
      when: never
  before_script:
    - echo "prepare shell scripts"
  script:
    # Run CI checker.
    - echo "Run CI checker"

    # Download artifacts.
    - echo "Download artifacts"

    # Post summary.
    - echo "Post summary"
#    - 'curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/5/issues/11/notes?body=note"'

