variables:
  SAST_EXCLUDED_ANALYZERS: "semgrep-sast,gosec-sast"
  DOCKER_DRIVER: overlay2

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never

include:
  - local: 'engine/.gitlab-ci.yml'
  - local: 'ui/.gitlab-ci.yml'
  - local: 'cloudformation/.gitlab-ci.yml'
  - local: 'checker/.gitlab-ci.yml'

empty-job:
  stage: test
  image: alpine:3.15
  script:
    - ""
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - engine/**/*
        - ui/**/*
        - cloudformation/**/*
        - checker/**/*
      when: never
