FROM docker:29.4.0@sha256:a6dd5322747a95cd8e3207bd8d415a8fd20ec34e9c00f06dc019cbd912013489

# Install dependencies.
RUN apk upgrade --no-cache && apk add --no-cache bash

WORKDIR /home/dblab

COPY ./bin/run-ci ./bin/run-ci

CMD ./bin/run-ci
