FROM docker:29.4.1@sha256:c77e5d7912f9b137cc67051fdc2991d8f5ae22c55ddf532bb836dcb693a04940

# Install dependencies.
RUN apk upgrade --no-cache && apk add --no-cache bash

WORKDIR /home/dblab

COPY ./bin/run-ci ./bin/run-ci

CMD ./bin/run-ci
