.only_cf_branch: &only_cf_branch
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - cloudformation/*

.only_cf_tag_rc: &only_cf_rc
  rules:
    - if: $CI_COMMIT_TAG =~ /^cf\/[0-9.]+[\-_]*[a-zA-Z]+[a-zA-Z0-9.\-_]*[a-zA-Z0-9]+$/

.only_cf_release: &only_cf_release
  rules:
    - if: $CI_COMMIT_TAG =~ /^cf\/[0-9.]+$/

### Test jobs.
test_cf_template:
  <<: *only_cf_branch
  stage: test
  script:
    - cd cloudformation
    - echo "run tests"

### Build jobs.
build_ami_branch:
  <<: *only_cf_branch
  stage: build
  script:
    - cd cloudformation
    - echo "Build AMI for branch"

build_ami_rc:
  <<: *only_cf_rc
  stage: build
  script:
    - cd cloudformation
    - echo "Build AMI RC"

build_ami_release:
  <<: *only_cf_release
  stage: build
  script:
    - cd cloudformation
    - echo "Build AMI"
